micronaut:
  application:
    name: departmentService
  server:
    port: 9003
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/microservice
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: '01111997'
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
